vpn:
  hosts:
    ru-vpn:
      ansible_host: 188.93.210.225
      vpn_host: 188.93.210.225
      vpn_port: 51820
    ru2-vpn:
      ansible_host: 90.156.226.43
      vpn_host: 90.156.226.43
      vpn_port: 51820
