vpn:
  hosts:
    nl-vpn:
      ansible_host: 214782.fornex.cloud
      vpn_host: 185.18.55.25
      vpn_port: 51820
    ru-vpn:
      ansible_host: 188.93.210.225
      vpn_host: 188.93.210.225
      vpn_port: 51820
    ee-vpn:
      ansible_host: 5.101.179.100
      vpn_host: 5.101.179.100
      vpn_port: 51820
